work_tracker/controllers/staff.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, g
from datetime import datetime

bp = Blueprint("staff", __name__, url_prefix="/staff")

# TODO: Check if user is signed in before accessing pages

@bp.route("/homepage", methods=["GET"])
def homepage():
    return render_template('index.html')


@bp.route("/view_employees", methods=["GET", "POST"])
def view_employees():

    # TODO: add try/catch, for now fail hard
    if request.method == "POST":

        filter = request.form.get("filter")
        query = request.form["search"]

        staffMembers = []

        # NOTE: queue the big ugly
        if filter == "id":
            staffMembers.append(g.staffModel.getStaffMember(query))
        elif filter == "name":
            staffMembers = g.staffModel.getStaffMembersByName(query)
        elif filter == "email":
            staffMembers = g.staffModel.getStaffMembersByEmail(query)
        elif filter == "contactNumber":
            staffMembers = g.staffModel.getStaffMembersByContactNumber(query)
        elif filter == "address":
            staffMembers = g.staffModel.getStaffMembersByAddress(query)
        elif filter == "suburb":
            staffMembers = g.staffModel.getStaffMembersBySuburb(query)
        elif filter == "postcode":
            staffMembers = g.staffModel.getStaffMembersByPostcode(query)
        elif filter == "state":
            staffMembers = g.staffModel.getStaffMembersByState(query)
        elif filter == "dob":
            staffMembers = g.staffModel.getStaffMembersByDOB(query)
        elif filter == "level":
            staffMembers = g.staffModel.getStaffMembersByLevel(query)

        return render_template('index-view-employees.html', staffMembers=staffMembers)

    staffMembers = g.staffModel.getStaffMembers()

    return render_template('index-view-employees.html', staffMembers=staffMembers)


@bp.route("/create", methods=["GET", "POST"])
def create():
    if request.method == 'POST':
        g.staffModel.createStaffMember(
            request.form['fname'],
            request.form['lname'],
            request.form['eaddress'],
            request.form['contact'],
            request.form['address1'] + ' ' + request.form['address2'],
            request.form['suburb'],
            request.form['postcode'],
            request.form['state'],
            request.form['dob'],
            request.form['level'])

    return render_template('index-create-employee.html')


@bp.route("/edit", methods=["GET", "POST"])
def edit():
    if request.method == 'POST':
        form = request.form

        g.staffModel.updateStaffMember(
            form['staffID'],
            form['fname'],
            form['lname'],
            form['eaddress'],
            form['contact'],
            form['address1'],
            form['suburb'],
            form['postcode'],
            form['state'],
            form['dob'],
            form['level']
        )

    # TODO: fix mess here
    staffID = request.args.get('staffID')
    if staffID is None:
        # Edit the current user
        staffID = g.user.staffID

    staffMember = g.staffModel.getStaffMember(staffID)

    return render_template('index-edit-employee.html', staffMember=staffMember)


# NOTE: For both availability and add_roster backends,
# request data is a array containing:
# dayName - can be Mon, Tues, Wed, Thurs, Fri, Sat, Sun

# startTime and endTime - value ranging from 0 - 8
# 0 represents 9am, 8 represents 5pm


@bp.route("/availability", methods=["GET", "POST"])
def availability():
    if request.method == "POST":
        # backend
        print(request.get_json())
    existingData = [{'dayName': 'Sat', 'startTime': 0, 'duration': 4}, {'dayName': 'Sun', 'startTime': 0, 'duration': 3}]
    return render_template('index-calendar.html', existingData=existingData, editable=True, weekDate="12 July - 18 July")


@bp.route("/add_roster", methods=["GET", "POST"])
def addRoster():
    if request.method == "POST":
        # backend
        print(request.get_json())
        print(request.args.get("staffID"))
    existingData = [{'dayName': 'Sat', 'startTime': 0, 'duration': 4}, {'dayName': 'Sun', 'startTime': 0, 'duration': 1}]
    return render_template('index-calendar.html', existingData=existingData, editable=True, weekDate="12 July - 18 July")


@bp.route("/payroll_query", methods=["GET", "POST"])
def payrollQuery():
    if request.method == "POST":
        day = datetime.strptime("2021-07-05", "%Y-%m-%d")  # a hack
        week = day.strftime("%W")
        g.payrollQueryModel.createPayrollQuery(g.user.staffID, week, request.get_json())
    shifts = g.timesheetModel.getTimesheet(1, "2021-07-05", "2021-07-11")  # hardcoded date for now
    jsonShifts = g.timesheetModel.shiftsToJson(shifts)
    return render_template('index-calendar.html', existingData=jsonShifts, showChanges=True, editable=True, weekDate="12 July - 18 July")


@bp.route("/roster", methods=["GET", "POST"])
def roster():
    if request.method == "POST":
        # backend
        print(request.get_json())
        print(request.args.get("staffID"))
    shifts = g.rosterModel.getRoster(1, "2021-07-05", "2021-07-11")  # hardcoded date for now
    jsonShifts = g.rosterModel.shiftsToJson(shifts)
    return render_template('index-calendar.html', existingData=jsonShifts, weekDate="12 July - 18 July", hideSubmit=True)


@bp.route("/view_query", methods=["GET", "POST"])
def viewQuery():
    payrollID = request.args.get("payrollID")
    if payrollID:
        if request.method == "POST":
            g.payrollQueryModel.approvePayrollQuery(payrollID)
        elif request.method == "GET":
            shifts = g.payrollQueryModel.getPayrollQueryDetails(payrollID)  # hardcoded date for now
            jsonShifts = g.payrollQueryModel.shiftsToJson(shifts)
            return render_template('index-calendar.html', existingData=jsonShifts, showChanges=True, weekDate="12 July - 18 July", submitButtonIsApprove=True)
    return "Need a payrollID"


@bp.route("/manager_query_list", methods=["GET", "POST"])
def managerQueryList():
    return render_template('index-manager-query-list.html')

@bp.route("/query_list", methods=["GET"])
def queryList():
    queries = g.payrollQueryModel.getPayrollQueriesByStaffID(g.user.staffID)
    return render_template("index-employee-query-list.html", queries=queries)

work_tracker/templates/index-calendar.html
{% extends "index.html" %}

{% block title %}Calendar{% endblock %}

{% block content %}

<br>
<h3 style="text-align: center;">{{ weekDate }}</h1>

<script>
    class Week {
        static times = ['9am', '10am', '11am', '12am', '1pm', '2pm', '3pm', '4pm', '5pm']
        static days = ['Mon', 'Tues', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']

        constructor() {
            const content = document.getElementById("content")

            // Times
            const columnsDiv = document.createElement("div")
            columnsDiv.className = "columns col-gapless"
            content.appendChild(columnsDiv)
            // Empty column
            const emptyColumn = document.createElement("div")
            emptyColumn.className = "column col-1"
            columnsDiv.appendChild(emptyColumn)
            // Time columns
            for(const time of Week.times) {
                const column = document.createElement("div")
                column.className = "column col-1"
                const text = document.createTextNode(time)
                column.appendChild(text)
                columnsDiv.appendChild(column)
            }

            // Fill out times
            this.days = []
            for(const dayName of Week.days) {
                this.days.push(new Day(content, this, dayName))
            }
        }

        updateChanges() {
            const tableBody = document.getElementById("changes")
            tableBody.textContent = ''  // clear table
            this.days.forEach((day) => {
                const existingDay = existingData.find((existingDay) => existingDay.dayName == day.name)
                if (day.hasBlock || existingDay) {
                    // row
                    const row = document.createElement("tr")
                    tableBody.appendChild(row)
                    // date
                    const date = document.createElement("td")
                    date.textContent = day.name
                    row.appendChild(date)
                    // original time
                    
                    const originalTime = document.createElement("td")
                    if (existingDay) {
                        originalTime.textContent = Week.times[existingDay.startTime] + ' - ' + Week.times[existingDay.startTime + existingDay.duration]
                        
                    }
                    row.appendChild(originalTime)
                    // new time
                    const newTime = document.createElement("td")
                    if (day.hasBlock) {
                        newTime.textContent = Week.times[day.startTime] + ' - ' + Week.times[day.endTime + 1]
                    } else {
                        newTime.textContent = 'Removed'
                    }
                    row.appendChild(newTime)
                    
                    // difference
                    const difference = document.createElement("td")
                    difference.textContent = (day.endTime - day.startTime + 1) - existingDay.duration
                    row.appendChild(difference)
                }
            })
        }
    }

    class Day {
        constructor(parent, week, dayName) {
            this.week = week
            this.hasBlock = false
            this.startTime = null
            this.endTime = null
            this.name = dayName
            // Create row
            const columnsDiv = document.createElement("div")
            columnsDiv.className = "columns col-gapless"
            parent.appendChild(columnsDiv)
            // Fill out day
            const dayColumn = document.createElement("div")
            dayColumn.className = "column col-1"
            const text = document.createTextNode(dayName)
            dayColumn.appendChild(text)
            columnsDiv.appendChild(dayColumn)

            this.slots = []
            for (let i = 0; i < Week.times.length - 1; i++) {
                this.slots[i] = new Slot(columnsDiv, this, parseInt(i))
            }
        }

        createSlot(startTime, duration) {
            this.startTime = startTime
            this.endTime = startTime + duration - 1  // eheheh, its a hack
            this.hasBlock = true

            for (let i = startTime; i <= this.endTime; i++) {
                this.slots[i].activate()
            }
        }

        handleClick(time) {
            // this code is shocking
            if (!this.hasBlock) {
                this.createSlot(time, 1)
            } else if (time >= this.startTime && time <= this.endTime) {
                // Decrease time
                if (this.startTime == this.endTime) {
                    const slot = this.slots[time]
                    slot.deactivate()
                    this.hasBlock = false
                } else if ((time - this.startTime) <= (this.endTime - time)) {
                    // Shrink start time
                    for(let i = time; i >= this.startTime; i--) {
                        const slot = this.slots[i]
                        slot.deactivate()
                    }
                    this.startTime = time + 1  // shrink to next slot, this is some real sketchy stuff
                } else {
                    // Shrink end time
                    for(let i = this.endTime; i >= time; i--) {
                        const slot = this.slots[i]
                        slot.deactivate()
                    }
                    this.endTime = time - 1  // shrink to previous slot
                }
            } else {
                // Extend time
                if (time < this.startTime) {
                    for(let i = time; i < this.startTime; i++) {
                        const slot = this.slots[i]
                        slot.activate()
                    }
                    this.startTime = time
                } else {
                    for(let i = time; i > this.endTime; i--) {
                        const slot = this.slots[i]
                        slot.activate()
                    }
                    this.endTime = time
                }
            }

            {% if showChanges %}
                this.week.updateChanges()
            {% endif %}
        }
    }

    class Slot {
        constructor(parent, day, time) {
            this.active = false
            // 1 hour block
            const recordColumn = document.createElement("div")
            recordColumn.className = "column col-1"
            parent.appendChild(recordColumn)
            // Button
            {% if editable %}
            const button = document.createElement("button")
            button.className = "btn btn-link"
            button.onclick = () => day.handleClick(time)
            const text = document.createTextNode('+')
            button.appendChild(text)
            recordColumn.appendChild(button)
            {% endif %}
            // Save
            this.element = recordColumn
        }

        activate() {
            this.active = true
            const slotElement = this.element
            {% if editable %}
            slotElement.firstChild.innerText = "-"
            {% endif %}
            slotElement.style.backgroundColor = "powderblue"
        }

        deactivate() {
            this.active = false
            const slotElement = this.element
            slotElement.firstChild.innerText = "+"
            slotElement.style.backgroundColor = null
        }
    }

    // Build the cool time thing
    const week = new Week()
    // Insert existing data
    const existingData = {{ existingData|tojson }}
    existingData.forEach((day) => {
        // quite the hack
        switch (day.dayName) {
            case "Mon":
                dayName = 0
                break
            case "Tues":
                dayName = 1
                break
            case "Wed":
                dayName = 2
                break
            case "Thu":
                dayName = 3
                break
            case "Fri":
                dayName = 4
                break
            case "Sat":
                dayName = 5
                break
            case "Sun":
                dayName = 6
                break
        }

        week.days[dayName].createSlot(day.startTime, day.duration)
    })

    // Update changes on page load
    {% if showChanges %}
        document.addEventListener('DOMContentLoaded', function() {
            week.updateChanges()
        })
    {% endif %}

    function send() {
        let blocks = []
        week.days.forEach((day) => {
            if (day.hasBlock) {
                blocks.push({
                    dayName: day.name,
                    startTime: day.startTime,
                    duration: day.endTime - day.startTime + 1
                })
            }
        })
        var xmlhttp = new XMLHttpRequest();   // new HttpRequest instance 
        xmlhttp.open("POST", "{{ request.url }}");
        xmlhttp.setRequestHeader("Content-Type", "application/json");
        xmlhttp.send(JSON.stringify(blocks));
    }
</script>

{% if showChanges %}
    Changes:
    <table class="table">
        <thead>
        <tr>
            <th>Date</th>
            <th>Original Time</th>
            <th>New Time</th>
            <th>Difference</th>
        </tr>
        </thead>
        <tbody id="changes">
        </tbody>
    </table>
{% endif %}
{% if not hideSubmit %}

<!-- We have gone to a new low -->
{% if submitButtonIsApprove %}
<button class="btn btn-success" onClick="send()">Approve</button>
{% else %}
<button class="btn btn-success" onClick="send()">Submit</button>
{% endif %}

{% endif %}

{% endblock %}

work_tracker/templates/index-create-employee.html
{% extends "index.html" %}

{% block title %}Employee{% endblock %}

{% block content %}

<body>
<link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre.min.css">
<link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre-exp.min.css">
<link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre-icons.min.css">

<center>
<form method="post">
<h1>Employee Information</h1>
<br><br>
  <label for="fname">First Name:</label>
  <input type="text" id="fname" name="fname" size="50">
  <label>Last Name:</label>
  <input type="text" id="lname" name="lname" maxlength="360" size="50"><br><br>
  <label>Email Address:</label>
  <input type="text" id="eaddress" name="eaddress" maxlength="360" size="60">

  <label>Contact Number:</label>
  <input type="text" id="contact" name="contact" maxlength="360" size="31"><br><br>
  <label>Address 1:</label>
  <input type="text" id="address1" name="address1" maxlength="360" size="51">
  <label>Address 2:</label>
  <input type="text" id="address2" name="address2" maxlength="360" size="51" placeholder="This address is optional">
    <br><br>


  <label>Suburb</label>
  <input type="text" id="suburb" name="suburb" maxlength="360" size="31">


  <label>Postcode:</label>
  <input type="text" id="postcode" name="postcode" maxlength="360" size="31">

  <label>State:</label>
  <input type="text" id="state" name="state" maxlength="360" size="21" placeholder="e.g. QLD or NSW "> <br><br>

  <label>Date of Birth:</label>
  <input type="text" id="dob" name="dob" placeholder="DD/MM/YYYY" maxlength="360" size="31">

  <label>Employee Level:</label>
  <input type="text" id="level" name="level" maxlength="360" size="31">

<button class="btn btn-success">Submit</button>

<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
    <p>Kmart © 2008</p>
</center>

</body>
</html>
{% endblock %}

work_tracker/templates/index-edit-employee.html
{% extends "index.html" %}

{% block title %}Employee{% endblock %}

{% block content %}

<link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre.min.css">
<link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre-exp.min.css">
<link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre-icons.min.css">

<center>
<form method="post">
  <h1>Employee Information</h1>
  <br><br>

  <label for="fname">First Name:</label>
  <input type="text" id="fname" name="fname" size="50" value="{{ staffMember.firstName }}">
  <label>Last Name:</label>
  <input type="text" id="lname" name="lname" maxlength="360" size="50" value="{{ staffMember.lastName }}"><br><br>
  <label>Email Address:</label>
  <input type="text" id="eaddress" name="eaddress" maxlength="360" size="60" value="{{ staffMember.email }}">

  <label>Contact Number:</label>
  <input type="text" id="contact" name="contact" maxlength="360" size="31" value="{{ staffMember.contactNumber }}"><br><br>
  <label>Address</label>
  <input type="text" id="address1" name="address1" maxlength="360" size="51" value="{{ staffMember.address }}">
    <br><br>


  <label>Suburb</label>
  <input type="text" id="suburb" name="suburb" maxlength="360" size="31" value="{{ staffMember.suburb }}">


  <label>Postcode:</label>
  <input type="text" id="postcode" name="postcode" maxlength="360" size="31" value="{{ staffMember.postcode }}">

  <label>State:</label>
  <input type="text" id="state" name="state" maxlength="360" size="21" placeholder="e.g. QLD or NSW " value="{{ staffMember.state }}"> <br><br>

  <label>Date of Birth:</label>
  <input type="text" id="dob" name="dob" placeholder="DD/MM/YYYY" maxlength="360" size="31" value="{{ staffMember.dob }}">

  <label>Employee Level:</label>
  <!-- TODO: Give option between employee and manager -->
  <input type="text" id="level" name="level" maxlength="360" size="31" value="{{ staffMember.isManager }}">

  <input type="hidden" name="staffID" value="{{ staffMember.staffID }}">

  <button class="btn btn-success">Submit</button>

</form>

<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
    <p>Kmart © 2008</p>
</center>
{% endblock %}

work_tracker/templates/index-employee-query-list.html
{% extends "index.html" %}

{% block title %}Employee Payroll Summary{% endblock %}

{% block content %}

<link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre.min.css">
<link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre-exp.min.css">
<link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre-icons.min.css">
<html>
<head>
    <meta charset="UTF-8">
    <title>Employee Pay Summary</title>
</head>

<body>
<center>
<h1>Your Payroll Query Summary</h1>

<br><br>

<table class="table table-striped table-h ver" style="width:500px">
  <thead>
    <tr>
      <th>Employee Name</th>
      <th>Date Submitted</th>
      <th>Approval Status</th>
    </tr>
  </thead>
  <tbody>


  {% for query in queries %}
    <tr class="active">
      <td>{{ query.staffID }}</td>
      <td>{{ query.date }}</td>
      <td>
        {% if query.status == 1 %}
          <td>Approved</td>
        {% else %}
      <!-- link to view query page -->
      <a href="{{ url_for('staff.viewQuery', payrollID=query.payrollID) }}" class="btn btn-link">Not Approved</a>
        {% endif %}
      </td>
    </tr>
  {% endfor %}
</table>

</center>

</body>
</html>

{% endblock %}

work_tracker/templates/index-employee.html
{% extends "index.html" %}

{% block title %}Employee{% endblock %}

{% block content %}

<body>
<link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre.min.css">
<link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre-exp.min.css">
<link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre-icons.min.css">

<center>
<form>
<h1>Employee Information</h1>
<br><br>
  <label for="fname">First Name:</label>
  <input type="text" id="fname" name="fname" size="50">
  <label>Last Name:</label>
  <input type="text" id="lname" name="lname" maxlength="360" size="50"><br><br>
  <label>Email Address:</label>
  <input type="text" id="eaddress" name="eaddress" maxlength="360" size="60">

  <label>Contact Number:</label>
  <input type="text" id="contact" name="contact" maxlength="360" size="31"><br><br>
  <label>Address 1:</label>
  <input type="text" id="address1" name="address1" maxlength="360" size="51">
  <label>Address 2:</label>
  <input type="text" id="address2" name="address2" maxlength="360" size="51" placeholder="This address is optional">
    <br><br>


  <label>Suburb</label>
  <input type="text" id="suburb" name="suburb" maxlength="360" size="31">


  <label>Postcode:</label>
  <input type="text" id="postcode" name="postcode" maxlength="360" size="31">

  <label>State:</label>
  <input type="text" id="state" name="state" maxlength="360" size="21" placeholder="e.g. QLD or NSW ">

<button class="btn btn-success">Submit</button>

<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
    <p>Kmart © 2008</p>
</center>

</body>
</html>
{% endblock %}

work_tracker/templates/index-manager-query-list.html
{% extends "index.html" %}

{% block title %}Employee Payroll Summary{% endblock %}

{% block content %}

<link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre.min.css">
<link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre-exp.min.css">
<link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre-icons.min.css">
<html>
<head>
    <meta charset="UTF-8">
    <title>Employee Pay Summary</title>
</head>

<body>
<center>
<h1>Your Payroll Query Summary</h1>

<br><br>

<table class="table table-striped table-hover" style="width:500px">
  <thead>
    <tr>
      <th>Employee Name</th>
      <th>Date Submitted</th>
      <th>Approval Status</th>
    </tr>
  </thead>
  <tbody>

    <tr class="active">
      <td>John Smith</td>
      <td>25 June </td>
      <!-- link to view query test page -->
      <td><a href="{{ url_for('staff.viewQuery') + '?payrollID=1' }}" class="btn btn-link">Not Approved</a></td>
    </tr>


    <tr class="active">
      <td>John Smith</td>
      <td>30 March </td>
      <td>Approved</td>
    </tbody>
</table>

</center>

</body>
</html>

{% endblock %}

work_tracker/templates/index-view-employees.html
{% extends "index.html" %}

{% block title %}View Employees{% endblock %}

{% block content %}

<br>
<div class="columns">
    <div class="column col-6">
        <form method="POST" class="form-horizontal">
            <div class="form-group">
              <div class="col-1 col-sm-12">
                <label class="form-label" for="search">Search</label>
              </div>
              <div class="col-3 col-sm-12">
                <input class="form-input" type="text" name="search" id="search">
              </div>
            </div>
            <div class="form-group">
              <div class="col-1 col-sm-12">
                <label class="form-label" for="filter">Filter</label>
              </div>
              <div class="col-3 col-sm-12">
                <select class="form-select" name="filter" id="search">
                  <option value="id">ID</option>
                  <option value="name">Name</option>
                  <option value="email">Email</option>
                  <option value="contactNumber">Contact Number</option>
                  <option value="address">Address</option>
                  <option value="suburb">Suburb</option>
                  <option value="postcode">Postcode</option>
                  <option value="state">State</option>
                  <option value="dob">DOB</option>
                  <option value="level">Employee Level</option>
                </select>
              </div>
            </div>
            <div class="form-group">
              <div class="col-4 col-sm-12">
                <button type="submit" class="btn">Search</button>
              </div>
            </div>
        </form>
    </div>
  </div>


<table class="table">
    <thead>
      <tr>
        <th>Employee ID</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th>Contact Number</th>
        <th>Address</th>
        <th>Suburb</th>
        <th>Postcode</th>
        <th>State</th>
        <th>Date of Birth</th>
        <th>Employee Level</th>
      </tr>
    </thead>
    <tbody>
    {% for staffMember in staffMembers %}
      <tr class="active">
        <th>{{ staffMember.staffID }}</th>
        <th>{{ staffMember.firstName}}</th>
        <th>{{ staffMember.lastName }}</th>
        <th>{{ staffMember.email }}</th>
        <th>{{ staffMember.contactNumber }}</th>
        <th>{{ staffMember.address }}</th>
        <th>{{ staffMember.suburb }}</th>
        <th>{{ staffMember.postcode }}</th>
        <th>{{ staffMember.state }}</th>
        <th>{{ staffMember.dob }}</th>
        {% if g.user.isManager == True %}
          <th>Manager</th>
        {% else %}
          <th>Employee</th>
        {% endif %}
        <th>
          <form action="{{ url_for('staff.edit') }}">
            <input type="hidden" name="staffID" value="{{ staffMember.staffID }}">
            <button class="btn" type="submit">Edit</button>
          </form>
          <form action="{{ url_for('staff.addRoster') }}">
            <input type="hidden" name="staffID" value="{{ staffMember.staffID }}">
            <button class="btn" type="submit">Add Roster</button>
          </form>
        </th>
      </tr>
    {% endfor %}
    </tbody>
  </table>

{% endblock %}

work_tracker/templates/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- Remove favicon error message -->
        <link rel="shortcut icon" href="#">

        <!-- Spectre.css import -->
        <link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre.min.css">
        <link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre-exp.min.css">
        <link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre-icons.min.css">

        <title>Work Tracker | {% block title %}{% endblock %}</title>

    </head>
    
    <body>
        <div class="container grid-xl">
            <header class="navbar">
                <section class="navbar-section">
                    <a href="{{ url_for('staff.homepage') }}" class="navbar-brand mr-2">Work Tracker</a>
                    <a href="{{ url_for('staff.homepage') }}" class="btn btn-link">Home</a>
                    <a href="{{ url_for('staff.roster') }}" class="btn btn-link">Roster</a>
                    <a href="{{ url_for('staff.availability') }}" class="btn btn-link">Availability</a>
                    <a href="{{ url_for('staff.payrollQuery') }}" class="btn btn-link">Payroll Query</a>

                    {% if g.user.isManager %}
                        <a href="{{ url_for('staff.view_employees') }}" class="btn btn-link">View Employees</a>
                        <a href="{{ url_for('staff.managerQueryList') }}" class="btn btn-link">Queries</a>
                    {% else %}
                        <!-- Replace with link to employee query list -->
                        <a href="{{ url_for('staff.queryList') }}" class="btn btn-link">Queries</a>
                    {% endif %}

                    

                    
                    <a href="{{ url_for('signOut') }}" class="btn btn-link">Sign Out</a>
                </section>
                <section class="navbar-section">
                    <div class="input-group input-inline">
                        <a href="{{ url_for('staff.edit') }}" class="btn btn-link">Welcome {{ g.user.firstName }}</a>
                    </div>
                </section>
            </header>
        
            <div id="content">
                {% block content %}
 
                {% endblock %}
            </div>
        </div>
    </body>
</html>